# build-bin

on:
  release:
    types: [created]
  workflow_dispatch:
  push:

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: cmd/remoteControl
          binary_name: "remoteControl"
          goos: linux
          goarch: amd64