# build-bin
on: [push]

permissions:
  contents: write
  packages: write

env:
  cmd_dir: ./cmd/remoteControl

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20]
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: go build ${{ env.cmd_dir }}